# You can set the hostname of docker host by using this command `sudo hostname <name>`
version: "3"
services:

  nserver:
    image: cloudwattfr/ntpserver:latest
    ports:
      - 2200:2200
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  gui:
    image: mluthra/tcep-gui
    ports:
       - 3000:3000
    networks:
       - main
    deploy:
      replicas: 1
      restart_policy:
         condition: on-failure
    privileged: true

  simulator:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.simulation.tcep.SimulationRunner
      - ARGS=--dir ./logs --mode 7 --ip simulator --port 2500 --query AccidentDetection  --eventRate 1 --mapek requirementBased --req hops --transitionStrategy SMS --transitionExecutionMode 1 --duration 100
      - LOG_FILE_PATH=/app/logs
    volumes:
       - $HOME/logs:/app/logs
    ports:
       - 25001:25001
    networks:
       - main
    deploy:
      replicas: 1
      restart_policy:
         condition: on-failure
    privileged: true

  consumer:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.machinenodes.ConsumerApp
      - ARGS=--dir ./logs --ip consumer --port 2700 --kind Accident --eventRate 1000
      - LOG_FILE_PATH=/app/logs
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  speedPublisher1:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--ip speedPublisher1 --port 2501 --kind SpeedPublisher --numberOfPublishers 1 --eventRate 1000
      - LOG_FILE_PATH=/app/logs
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  speedPublisher2:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--ip speedPublisher2 --port 2502 --kind SpeedPublisher --numberOfPublishers 2 --eventRate 1000
      - LOG_FILE_PATH=/app/logs
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  speedPublisher3:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--ip speedPublisher3 --port 2503 --kind SpeedPublisher --numberOfPublishers 3 --eventRate 1000
      - LOG_FILE_PATH=/app/logs
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  densityPublisher:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--ip densityPublisher --port 2504 --kind DensityPublisher --numberOfPublishers 0 --eventRate 1000
      - LOG_FILE_PATH=/app/logs
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  worker:
    image: mluthra/tcep
    environment:
      - MAIN=tcep.machinenodes.EmptyApp
      - ARGS=--port 3400 --eventRate 1000
      - LOG_FILE_PATH=/app/logs
    depends_on:
      - simulator
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    privileged: true


networks:
  main:
