# You can set the hostname of docker host by using this command `sudo hostname <name>`
version: "3"
services:

  nserver:
    image: cloudwattfr/ntpserver:latest
    ports:
      - 2200:2200
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  viv:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.VivaldiApp
      - ARGS=--port 2549 --ip viv
    depends_on:
      - nserver
    ports:
      - 2549:2549
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  gui:
    image: tcep-gui
    ports:
      - 3000:3000
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  simulator:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.simulation.tcep.SimulationRunner
      - ARGS= ./logs 7 simulator 2202
    depends_on:
      - viv
    volumes:
      - $HOME/logs:/app/logs
    ports:
      - 2202:2202
      - 25001:25001
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  DoorSensor:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--port 3300 --name DoorSensor --ip DoorSensor --host node1
    depends_on:
      - viv
    ports:
      - 3300:3300
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  SanitizerSensor:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--port 3301 --name SanitizerSensor --ip SanitizerSensor --host node2
    depends_on:
      - viv
    ports:
      - 3301:3301
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  app3:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.EmptyApp
      - ARGS=--port 3303 --ip app3
    depends_on:
      - viv
    volumes:
      - $HOME/logs:/app/logs
    ports:
      - 3303:3303
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  app4:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.EmptyApp
      - ARGS=--port 3304 --ip app4
    depends_on:
      - viv
    volumes:
      - $HOME/logs:/app/logs
    ports:
      - 3304:3304
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  app5:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.EmptyApp
      - ARGS=--port 3305 --ip app5
    depends_on:
      - viv
    volumes:
      - $HOME/logs:/app/logs
    ports:
      - 3305:3305
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  app6:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.EmptyApp
      - ARGS=--port 3306 --ip app6
    depends_on:
      - viv
    volumes:
      - $HOME/logs:/app/logs
    ports:
      - 3306:3306
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true

  app7:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.EmptyApp
      - ARGS=--port 3307 --ip app7
    depends_on:
      - viv
    volumes:
      - $HOME/logs:/app/logs
    ports:
      - 3307:3307
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true




networks:
  main: